### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by hanishtharwani123**
there was a typo (grammatical mistake)

### CODE REVIEW

**Comment by gokulrajpuviyarasu** [comment]
@hanishtharwani123 please don't spam the repo. check the contribution guidelines & other open pull request before creating one

**Comment by gokulrajpuviyarasu** [comment]
> 

Typo and grammatical error are two different thing

**Comment by hanishtharwani123** [comment]
Ok

**Comment by hanishtharwani123** [comment]
Ok, understand

**Comment by evan-gray** [comment]
This repo is being archived in favor of docs.wormhole.com

**Pull request closed without merging**
